/* Copyright 2021 Ruland
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "quantum.h"

#define LAYOUT( \
      K00,    K01, K02, K03, K04, K05,                 K09, K0A, K0B, K0C, K0D, K0E,            \
     K10,     K11, K12, K13, K14, K15,                 K19, K1A, K1B, K1C, K1D, K1E, K1F,       \
    K20,      K21, K22, K23, K24, K25,                 K29, K2A, K2B, K2C, K2D, K2E, K3E, K2F,  \
                K31, K32,  K34,                        K3A,          K3C,  K3D                  \
) { \
    { K00,   K01,   K02,   K03,   K04,   K05,   KC_NO, KC_NO, KC_NO, K09,   K0A,   K0B,   K0C,   K0D,   K0E,   KC_NO }, \
    { K10,   K11,   K12,   K13,   K14,   K15,   KC_NO, KC_NO, KC_NO, K19,   K1A,   K1B,   K1C,   K1D,   K1E,   K1F   }, \
    { K20,   K21,   K22,   K23,   K24,   K25,   KC_NO, KC_NO, KC_NO, K29,   K2A,   K2B,   K2C,   K2D,   K2E,   K2F   }, \
    { KC_NO, K31,   K32,   KC_NO, K34,   KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, K3A,   KC_NO, K3C,   K3D,   K3E,   KC_NO }, \
}

// generated by KBFirmware JSON to QMK Parser
// https://noroadsleft.github.io/kbf_qmk_converter/